project:
  type: website
  output-dir: docs

website:
  title: "Lim's Code Archive"
  search: true
  page-navigation: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/limyj0708
      - icon: Linkedin
        href: https://www.linkedin.com/feed/

format:
  html:
    theme: cosmo
    css: styles.css